# 网站信息 (Site)
title: My Awesome Blog          # 网站标题
subtitle: 'A blog about tech and life' # 网站副标题
description: '记录技术、分享生活、探索世界'  # 网站描述，主要用于SEO
keywords:
  - 技术
  - 编程
  - 生活
author: John Doe               # 你的名字
language: zh-CN                 # 网站语言 (zh-CN, en, ja ...)
timezone: 'America/Los_Angeles' # 网站时区，请根据你的位置修改，如 Asia/Shanghai

# 网址信息 (URL)
# !!! 在部署前，请务必将 url 修改为你的最终域名
url: http://example.com         # 你的网站网址
root: /                         # 网站根目录。如果你的网站在子目录下，比如 http://example.com/blog，则设为 /blog/
permalink: :year/:month/:day/:title/ # 文章的永久链接格式
permalink_defaults:
  lang: en                      # 永久链接中各部分的默认值

# 目录设置 (Directory)
source_dir: source              # 源文件目录，文章和页面都放在这里
public_dir: public              # 生成的静态文件目录
tag_dir: tags                   # 标签目录
archive_dir: archives           # 归档目录
category_dir: categories        # 分类目录
code_dir: downloads/code        # 代码下载目录
i18n_dir: :lang                 # 国际化(i18n)目录
skip_render:                    # 跳过渲染的文件或目录，支持通配符

# 文章设置 (Writing)
new_post_name: :title.md        # 新文章的文件名格式
default_layout: post            # 默认布局
titlecase: false                # 是否将标题转换为 Title Case
external_link:
  enable: true                  # 是否在新标签页中打开外部链接
  field: site                   # 应用范围：site（整个网站）或 post（仅文章）
  exclude: ''                   # 例外规则
filename_case: 0                # 文件名大小写转换 (0: 无转换, 1: 小写, 2: 大写)
render_drafts: false            # 是否渲染草稿
post_asset_folder: true         # 是否启用 Asset Folder，便于管理文章图片
relative_link: false            # 是否将链接转换为相对路径
future: true                    # 是否显示未来的文章
highlight:                      # 代码高亮设置
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

# 分类和标签 (Category & Tag)
default_category: uncategorized # 默认分类
category_map:                   # 分类别名
tag_map:                        # 标签别名

# 分页 (Pagination)
# 每页显示的文章数量 (0 = 关闭分页)
per_page: 10
pagination_dir: page

# 扩展配置 (Extensions)
# 主题 - 名字必须和你放在 themes 文件夹下的主题文件夹名一致
theme: landscape                # 默认是 landscape，请修改为你下载的主题名

# 部署配置 (Deployment)
# !!! 部署前需要先安装对应的部署插件，例如：npm install hexo-deployer-git --save
deploy:
  type: git
  repo:                         # 例如：https://github.com/<your-username>/<your-repo>.git
  branch: main                  # 或者 gh-pages