# my-special-theme 的配置文件

hero:
  name: Shizhe Zhang
  tagline: A master student at Berkeley
  profile_pic: /images/profile-pic.jpg
  background: /images/background.png
  social_links:
    github: https://github.com/zzhansys
    linkedin: https://www.linkedin.com/in/%E5%A3%AB%E5%93%B2-%E5%BC%A0-658b17365/

about:
  title: 关于我
  background: /images/background.jpg
  sticker: /images/sticker-book.jpg
  content: |
    你好 这里还没有写。
    
    这是第二段。**加粗** 或 *斜体*。

# 在这里继续添加 projects 和 contact 部分的配置